# -----------------------------------------------------------
# This file is generated by the Qt Visual Studio Integration.
# -----------------------------------------------------------


#Header files
HEADERS += ./headers/fmModelImpl.h \
    ./headers/Maths.h

#Source files
SOURCES += ./sources/fmModelImpl.cpp \
    ./sources/main.cpp \
    ./sources/Maths.cpp

#Forms
FORMS += ./forms/fmModel.ui
